# site settings
title: Compiler
subtitle: 
email: contact@compiler.dev
description: Highly driven, computer scientist<br />
baseurl: "" # the subpath of your site, e.g. /blog
url: https://compiler.dev # the base hostname & protocol for your site
author:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/Compiler
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/luke-roche
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

repository: compiler/compiler.github.io

sass:
  style: compressed
github: [metadata]
exclude: [vendor]
exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- vendor

